In [262]:
import pandas as pd

In [263]:
def Null_remover(df):
  for i in df.columns:
    if df[i].dtype=='object':
      df[i]=df[i].fillna(df[i].mode()[0])
    else:
      df[i]=df[i].fillna(df[i].mean())
  return df


from sklearn.preprocessing import LabelEncoder, OneHotEncoder
def Label(df,i):
  le=LabelEncoder()
  df[i]=le.fit_transform(df[i])
  return df[i]


def ohe(df,cols):
  df = pd.get_dummies(df,columns=cols,prefix=cols,drop_first=False)
  return df

Customer Personality Analysis Dataset

In [264]:
df1=pd.read_csv('/content/marketing_campaign.csv', delimiter='\t')
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2240 entries, 0 to 2239
Data columns (total 29 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ID                   2240 non-null   int64
 1   Year_Birth           2240 non-null   int64
 2   Education            2240 non-null   object
 3   Marital_Status       2240 non-null   object
 4   Income               2216 non-null   float64
 5   Kidhome              2240 non-null   int64
 6   Teenhome             2240 non-null   int64
 7   Dt_Customer          2240 non-null   object
 8   Recency              2240 non-null   int64
 9   MntWines             2240 non-null   int64
 10  MntFruits            2240 non-null   int64
 11  MntMeatProducts      2240 non-null   int64
 12  MntFishProducts      2240 non-null   int64
 13  MntSweetProducts     2240 non-null   int64
 14  MntGoldProds         2240 non-null   int64
 15  NumDealsPurchases    2240 non-null   int64
 16  NumWebPurchases      2240 non-null   int64
 17  NumCatalogPurchases  2240 non-null   int64
 18  NumStorePurchases    2240 non-null   int64
 19  NumWebVisitsMonth    2240 non-null   int64
 20  AcceptedCmp3         2240 non-null   int64
 21  AcceptedCmp4         2240 non-null   int64
 22  AcceptedCmp5         2240 non-null   int64
 23  AcceptedCmp1         2240 non-null   int64
 24  AcceptedCmp2         2240 non-null   int64
 25  Complain             2240 non-null   int64
 26  Z_CostContact        2240 non-null   int64
 27  Z_Revenue            2240 non-null   int64
 28  Response             2240 non-null   int64
dtypes: float64(1), int64(25), object(3)
memory usage: 507.6+ KB

In [265]:
print(df1.isnull().sum().sum())
df1=Null_remover(df1)

24

In [266]:
df1.drop_duplicates(ignore_index=True,inplace=True)

In [267]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2240 entries, 0 to 2239
Data columns (total 29 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ID                   2240 non-null   int64
 1   Year_Birth           2240 non-null   int64
 2   Education            2240 non-null   object
 3   Marital_Status       2240 non-null   object
 4   Income               2240 non-null   float64
 5   Kidhome              2240 non-null   int64
 6   Teenhome             2240 non-null   int64
 7   Dt_Customer          2240 non-null   object
 8   Recency              2240 non-null   int64
 9   MntWines             2240 non-null   int64
 10  MntFruits            2240 non-null   int64
 11  MntMeatProducts      2240 non-null   int64
 12  MntFishProducts      2240 non-null   int64
 13  MntSweetProducts     2240 non-null   int64
 14  MntGoldProds         2240 non-null   int64
 15  NumDealsPurchases    2240 non-null   int64
 16  NumWebPurchases      2240 non-null   int64
 17  NumCatalogPurchases  2240 non-null   int64
 18  NumStorePurchases    2240 non-null   int64
 19  NumWebVisitsMonth    2240 non-null   int64
 20  AcceptedCmp3         2240 non-null   int64
 21  AcceptedCmp4         2240 non-null   int64
 22  AcceptedCmp5         2240 non-null   int64
 23  AcceptedCmp1         2240 non-null   int64
 24  AcceptedCmp2         2240 non-null   int64
 25  Complain             2240 non-null   int64
 26  Z_CostContact        2240 non-null   int64
 27  Z_Revenue            2240 non-null   int64
 28  Response             2240 non-null   int64
dtypes: float64(1), int64(25), object(3)
memory usage: 507.6+ KB

In [268]:
df1.columns = (df1.columns.str.strip().str.lower())

In [269]:
df1.columns

Index(['id', 'year_birth', 'education', 'marital_status', 'income', 'kidhome',
       'teenhome', 'dt_customer', 'recency', 'mntwines', 'mntfruits',
       'mntmeatproducts', 'mntfishproducts', 'mntsweetproducts',
       'mntgoldprods', 'numdealspurchases', 'numwebpurchases',
       'numcatalogpurchases', 'numstorepurchases', 'numwebvisitsmonth',
       'acceptedcmp3', 'acceptedcmp4', 'acceptedcmp5', 'acceptedcmp1',
       'acceptedcmp2', 'complain', 'z_costcontact', 'z_revenue', 'response'],
      dtype='object')

In [270]:
df1=ohe(df1,['education','marital_status'])
df1['dt_customer'] = pd.to_datetime(df1['dt_customer'], errors='coerce')

In [271]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2240 entries, 0 to 2239
Data columns (total 40 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   id                       2240 non-null   int64
 1   year_birth               2240 non-null   int64
 2   income                   2240 non-null   float64
 3   kidhome                  2240 non-null   int64
 4   teenhome                 2240 non-null   int64
 5   dt_customer              916 non-null    datetime64[ns]
 6   recency                  2240 non-null   int64
 7   mntwines                 2240 non-null   int64
 8   mntfruits                2240 non-null   int64
 9   mntmeatproducts          2240 non-null   int64
 10  mntfishproducts          2240 non-null   int64
 11  mntsweetproducts         2240 non-null   int64
 12  mntgoldprods             2240 non-null   int64
 13  numdealspurchases        2240 non-null   int64
 14  numwebpurchases          2240 non-null   int64
 15  numcatalogpurchases      2240 non-null   int64
 16  numstorepurchases        2240 non-null   int64
 17  numwebvisitsmonth        2240 non-null   int64
 18  acceptedcmp3             2240 non-null   int64
 19  acceptedcmp4             2240 non-null   int64
 20  acceptedcmp5             2240 non-null   int64
 21  acceptedcmp1             2240 non-null   int64
 22  acceptedcmp2             2240 non-null   int64
 23  complain                 2240 non-null   int64
 24  z_costcontact            2240 non-null   int64
 25  z_revenue                2240 non-null   int64
 26  response                 2240 non-null   int64
 27  education_2n Cycle       2240 non-null   bool
 28  education_Basic          2240 non-null   bool
 29  education_Graduation     2240 non-null   bool
 30  education_Master         2240 non-null   bool
 31  education_PhD            2240 non-null   bool
 32  marital_status_Absurd    2240 non-null   bool
 33  marital_status_Alone     2240 non-null   bool
 34  marital_status_Divorced  2240 non-null   bool
 35  marital_status_Married   2240 non-null   bool
 36  marital_status_Single    2240 non-null   bool
 37  marital_status_Together  2240 non-null   bool
 38  marital_status_Widow     2240 non-null   bool
 39  marital_status_YOLO      2240 non-null   bool
dtypes: bool(13), datetime64[ns](1), float64(1), int64(25)
memory usage: 501.1 KB

In [272]:
df1

,id,year_birth,income,kidhome,teenhome,dt_customer,recency,mntwines,mntfruits,mntmeatproducts,...,education_Master,education_PhD,marital_status_Absurd,marital_status_Alone,marital_status_Divorced,marital_status_Married,marital_status_Single,marital_status_Together,marital_status_Widow,marital_status_YOLO
0,5524,1957,58138.0,0,0,2012-04-09,58,635,88,546,...,False,False,False,False,False,False,True,False,False,False
1,2174,1954,46344.0,1,1,2014-08-03,38,11,1,6,...,False,False,False,False,False,False,True,False,False,False
2,4141,1965,71613.0,0,0,NaT,26,426,49,127,...,False,False,False,False,False,False,False,True,False,False
3,6182,1984,26646.0,1,0,2014-10-02,26,11,4,20,...,False,False,False,False,False,False,False,True,False,False
4,5324,1981,58293.0,1,0,NaT,94,173,43,118,...,False,True,False,False,False,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2235,10870,1967,61223.0,0,1,NaT,46,709,43,182,...,False,False,False,False,False,True,False,False,False,False
2236,4001,1946,64014.0,2,1,2014-10-06,56,406,0,30,...,False,True,False,False,False,False,False,True,False,False
2237,7270,1981,56981.0,0,0,NaT,91,908,48,217,...,False,False,False,False,True,False,False,False,False,False
2238,8235,1956,69245.0,0,1,NaT,8,428,30,214,...,True,False,False,False,False,False,False,True,False,False
2239,9405,1954,52869.0,1,1,NaT,40,84,3,61,...,False,True,False,False,False,True,False,False,False,False

Medical Appointment No Shows Dataset

In [273]:
df2=pd.read_csv('/content/KaggleV2-May-2016.csv')
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 110527 entries, 0 to 110526
Data columns (total 14 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   PatientId       110527 non-null  float64
 1   AppointmentID   110527 non-null  int64
 2   Gender          110527 non-null  object
 3   ScheduledDay    110527 non-null  object
 4   AppointmentDay  110527 non-null  object
 5   Age             110527 non-null  int64
 6   Neighbourhood   110527 non-null  object
 7   Scholarship     110527 non-null  int64
 8   Hipertension    110527 non-null  int64
 9   Diabetes        110527 non-null  int64
 10  Alcoholism      110527 non-null  int64
 11  Handcap         110527 non-null  int64
 12  SMS_received    110527 non-null  int64
 13  No-show         110527 non-null  object
dtypes: float64(1), int64(8), object(5)
memory usage: 11.8+ MB

In [274]:
# print(df2.isnull().sum().sum())
# df2=Null_remover(df2)

In [275]:
df2.drop_duplicates(ignore_index=True,inplace=True)

In [276]:
df2.columns = (df2.columns.str.strip().str.lower())
df2.columns

Index(['patientid', 'appointmentid', 'gender', 'scheduledday',
       'appointmentday', 'age', 'neighbourhood', 'scholarship', 'hipertension',
       'diabetes', 'alcoholism', 'handcap', 'sms_received', 'no-show'],
      dtype='object')

In [277]:
df2['gender']=Label(df2,'gender')
df2['neighbourhood']=Label(df2,'neighbourhood')
df2['no-show']=Label(df2,'no-show')
df2['appointmentday'] = pd.to_datetime(df2['appointmentday'], errors='coerce')
df2['scheduledday']=pd.to_datetime(df2['scheduledday'],errors='coerce')

In [278]:
df2['patientid']=df2['patientid'].astype('int')
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 110527 entries, 0 to 110526
Data columns (total 14 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   patientid       110527 non-null  int64
 1   appointmentid   110527 non-null  int64
 2   gender          110527 non-null  int64
 3   scheduledday    110527 non-null  datetime64[ns, UTC]
 4   appointmentday  110527 non-null  datetime64[ns, UTC]
 5   age             110527 non-null  int64
 6   neighbourhood   110527 non-null  int64
 7   scholarship     110527 non-null  int64
 8   hipertension    110527 non-null  int64
 9   diabetes        110527 non-null  int64
 10  alcoholism      110527 non-null  int64
 11  handcap         110527 non-null  int64
 12  sms_received    110527 non-null  int64
 13  no-show         110527 non-null  int64
dtypes: datetime64[ns, UTC](2), int64(12)
memory usage: 11.8 MB

In [279]:
df2

,patientid,appointmentid,gender,scheduledday,appointmentday,age,neighbourhood,scholarship,hipertension,diabetes,alcoholism,handcap,sms_received,no-show
0,29872499824296,5642903,0,2016-04-29 18:38:08+00:00,2016-04-29 00:00:00+00:00,62,39,0,1,0,0,0,0,0
1,558997776694438,5642503,1,2016-04-29 16:08:27+00:00,2016-04-29 00:00:00+00:00,56,39,0,0,0,0,0,0,0
2,4262962299951,5642549,0,2016-04-29 16:19:04+00:00,2016-04-29 00:00:00+00:00,62,45,0,0,0,0,0,0,0
3,867951213174,5642828,0,2016-04-29 17:29:31+00:00,2016-04-29 00:00:00+00:00,8,54,0,0,0,0,0,0,0
4,8841186448183,5642494,0,2016-04-29 16:07:23+00:00,2016-04-29 00:00:00+00:00,56,39,0,1,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
110522,2572134369293,5651768,0,2016-05-03 09:15:35+00:00,2016-06-07 00:00:00+00:00,56,43,0,0,0,0,0,1,0
110523,3596266328735,5650093,0,2016-05-03 07:27:33+00:00,2016-06-07 00:00:00+00:00,51,43,0,0,0,0,0,1,0
110524,15576631729893,5630692,0,2016-04-27 16:03:52+00:00,2016-06-07 00:00:00+00:00,21,43,0,0,0,0,0,1,0
110525,92134931435557,5630323,0,2016-04-27 15:09:23+00:00,2016-06-07 00:00:00+00:00,38,43,0,0,0,0,0,1,0
110526,377511518121127,5629448,0,2016-04-27 13:30:56+00:00,2016-06-07 00:00:00+00:00,54,43,0,0,0,0,0,1,0

Mall Customer Segmentation Data

In [280]:
df3=pd.read_csv('/content/Mall_Customers.csv')
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 5 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   CustomerID              200 non-null    int64
 1   Gender                  200 non-null    object
 2   Age                     200 non-null    int64
 3   Annual Income (k$)      200 non-null    int64
 4   Spending Score (1-100)  200 non-null    int64
dtypes: int64(4), object(1)
memory usage: 7.9+ KB

In [281]:
df3.columns = (df3.columns.str.strip().str.lower())
df3['gender']=Label(df3,'gender')

In [282]:
df3

     customerid  gender  age  annual income (k$)  spending score (1-100)
0             1       1   19                  15                      39
1             2       1   21                  15                      81
2             3       0   20                  16                       6
3             4       0   23                  16                      77
4             5       0   31                  17                      40
..          ...     ...  ...                 ...                     ...
195         196       0   35                 120                      79
196         197       0   45                 126                      28
197         198       1   32                 126                      74
198         199       1   32                 137                      18
199         200       1   30                 137                      83

[200 rows x 5 columns]

Netflix Movies and TV Shows

In [283]:
df4=pd.read_csv('/content/netflix_titles.csv')
df4.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8807 entries, 0 to 8806
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8807 non-null   object
 1   type          8807 non-null   object
 2   title         8807 non-null   object
 3   director      6173 non-null   object
 4   cast          7982 non-null   object
 5   country       7976 non-null   object
 6   date_added    8797 non-null   object
 7   release_year  8807 non-null   int64
 8   rating        8803 non-null   object
 9   duration      8804 non-null   object
 10  listed_in     8807 non-null   object
 11  description   8807 non-null   object
dtypes: int64(1), object(11)
memory usage: 825.8+ KB

In [284]:
print(df4.isnull().sum().sum())
df4=Null_remover(df4)

4307

In [285]:
print(df4.duplicated().sum())
df4.drop_duplicates(ignore_index=True,inplace=True)

0

In [286]:
df4['date_added']=pd.to_datetime(df4['date_added'],errors='coerce')

In [287]:
df4.columns = (df4.columns.str.strip().str.lower())
le=LabelEncoder()
for i in df4.columns:
  if df4[i].dtype=='object':
    df4[i]=le.fit_transform(df4[i])

In [288]:
df4.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8807 entries, 0 to 8806
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8807 non-null   int64
 1   type          8807 non-null   int64
 2   title         8807 non-null   int64
 3   director      8807 non-null   int64
 4   cast          8807 non-null   int64
 5   country       8807 non-null   int64
 6   date_added    8719 non-null   datetime64[ns]
 7   release_year  8807 non-null   int64
 8   rating        8807 non-null   int64
 9   duration      8807 non-null   int64
 10  listed_in     8807 non-null   int64
 11  description   8807 non-null   int64
dtypes: datetime64[ns](1), int64(11)
memory usage: 825.8 KB

In [289]:
df4

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,0,0,1975,2295,1699,603,2021-09-25,2020,7,210,274,2577
1,1111,1,1091,3392,409,426,2021-09-24,2021,11,110,414,1762
2,2222,1,2651,2105,6296,603,2021-09-24,2021,11,0,242,7341
3,3333,1,3506,3392,1699,603,2021-09-24,2021,11,0,297,3617
4,4444,1,3861,3392,4815,251,2021-09-24,2021,11,110,393,4416
...,...,...,...,...,...,...,...,...,...,...,...,...
8802,8671,0,8770,979,4677,603,2019-11-20,2007,8,70,269,895
8803,8672,1,8773,3392,1699,603,2019-07-01,2018,14,110,424,8483
8804,8673,0,8774,3631,3231,603,2019-11-01,2009,8,206,207,5228
8805,8674,0,8777,3247,7061,603,2020-01-11,2006,6,206,125,3315
8806,8675,0,8781,2926,7297,251,2019-03-02,2015,9,16,328,1004

Sales_Data

In [290]:
df5=pd.read_csv('/content/sales_data.csv',encoding='latin1')
df5.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2823 entries, 0 to 2822
Data columns (total 25 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   ORDERNUMBER       2823 non-null   int64
 1   QUANTITYORDERED   2823 non-null   int64
 2   PRICEEACH         2823 non-null   float64
 3   ORDERLINENUMBER   2823 non-null   int64
 4   SALES             2823 non-null   float64
 5   ORDERDATE         2823 non-null   object
 6   STATUS            2823 non-null   object
 7   QTR_ID            2823 non-null   int64
 8   MONTH_ID          2823 non-null   int64
 9   YEAR_ID           2823 non-null   int64
 10  PRODUCTLINE       2823 non-null   object
 11  MSRP              2823 non-null   int64
 12  PRODUCTCODE       2823 non-null   object
 13  CUSTOMERNAME      2823 non-null   object
 14  PHONE             2823 non-null   object
 15  ADDRESSLINE1      2823 non-null   object
 16  ADDRESSLINE2      302 non-null    object
 17  CITY              2823 non-null   object
 18  STATE             1337 non-null   object
 19  POSTALCODE        2747 non-null   object
 20  COUNTRY           2823 non-null   object
 21  TERRITORY         1749 non-null   object
 22  CONTACTLASTNAME   2823 non-null   object
 23  CONTACTFIRSTNAME  2823 non-null   object
 24  DEALSIZE          2823 non-null   object
dtypes: float64(2), int64(7), object(16)
memory usage: 551.5+ KB

In [291]:
df5.isnull().sum()
df5['ADDRESSLINE2'] = df5['ADDRESSLINE2'].fillna('Not Available')
df5['STATE'] = df5['STATE'].fillna('Unknown')
df5['POSTALCODE'] = df5['POSTALCODE'].fillna('Unknown')
df5['TERRITORY'] = df5['TERRITORY'].fillna('Unknown')

In [292]:
print(df5.duplicated().sum())
df5.drop_duplicates(ignore_index=True,inplace=True)

0

In [293]:
df5.columns = (df5.columns.str.strip().str.lower())
df5.columns

Index(['ordernumber', 'quantityordered', 'priceeach', 'orderlinenumber',
       'sales', 'orderdate', 'status', 'qtr_id', 'month_id', 'year_id',
       'productline', 'msrp', 'productcode', 'customername', 'phone',
       'addressline1', 'addressline2', 'city', 'state', 'postalcode',
       'country', 'territory', 'contactlastname', 'contactfirstname',
       'dealsize'],
      dtype='object')

In [294]:
df5['orderdate']=pd.to_datetime(df5['orderdate'],errors='coerce')
df5['phone']=pd.to_numeric(df5['phone'], errors='coerce')
df5['postalcode']=pd.to_numeric(df5['postalcode'], errors='coerce')

df5['phone']=df5['phone'].astype('Int64')
df5['postalcode']=df5['postalcode'].astype('Int64')

In [295]:
df5.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2823 entries, 0 to 2822
Data columns (total 25 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   ordernumber       2823 non-null   int64
 1   quantityordered   2823 non-null   int64
 2   priceeach         2823 non-null   float64
 3   orderlinenumber   2823 non-null   int64
 4   sales             2823 non-null   float64
 5   orderdate         2823 non-null   datetime64[ns]
 6   status            2823 non-null   object
 7   qtr_id            2823 non-null   int64
 8   month_id          2823 non-null   int64
 9   year_id           2823 non-null   int64
 10  productline       2823 non-null   object
 11  msrp              2823 non-null   int64
 12  productcode       2823 non-null   object
 13  customername      2823 non-null   object
 14  phone             1004 non-null   Int64
 15  addressline1      2823 non-null   object
 16  addressline2      2823 non-null   object
 17  city              2823 non-null   object
 18  state             2823 non-null   object
 19  postalcode        2282 non-null   Int64
 20  country           2823 non-null   object
 21  territory         2823 non-null   object
 22  contactlastname   2823 non-null   object
 23  contactfirstname  2823 non-null   object
 24  dealsize          2823 non-null   object
dtypes: Int64(2), datetime64[ns](1), float64(2), int64(7), object(13)
memory usage: 557.0+ KB

In [296]:
df5

,ordernumber,quantityordered,priceeach,orderlinenumber,sales,orderdate,status,qtr_id,month_id,year_id,...,addressline1,addressline2,city,state,postalcode,country,territory,contactlastname,contactfirstname,dealsize
0,10107,30,95.70,2,2871.00,2003-02-24,Shipped,1,2,2003,...,897 Long Airport Avenue,Not Available,NYC,NY,10022,USA,Unknown,Yu,Kwai,Small
1,10121,34,81.35,5,2765.90,2003-05-07,Shipped,2,5,2003,...,59 rue de l'Abbaye,Not Available,Reims,Unknown,51100,France,EMEA,Henriot,Paul,Small
2,10134,41,94.74,2,3884.34,2003-07-01,Shipped,3,7,2003,...,27 rue du Colonel Pierre Avia,Not Available,Paris,Unknown,75508,France,EMEA,Da Cunha,Daniel,Medium
3,10145,45,83.26,6,3746.70,2003-08-25,Shipped,3,8,2003,...,78934 Hillside Dr.,Not Available,Pasadena,CA,90003,USA,Unknown,Young,Julie,Medium
4,10159,49,100.00,14,5205.27,2003-10-10,Shipped,4,10,2003,...,7734 Strong St.,Not Available,San Francisco,CA,<NA>,USA,Unknown,Brown,Julie,Medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2818,10350,20,100.00,15,2244.40,2004-12-02,Shipped,4,12,2004,...,"C/ Moralzarzal, 86",Not Available,Madrid,Unknown,28034,Spain,EMEA,Freyre,Diego,Small
2819,10373,29,100.00,1,3978.51,2005-01-31,Shipped,1,1,2005,...,Torikatu 38,Not Available,Oulu,Unknown,90110,Finland,EMEA,Koskitalo,Pirkko,Medium
2820,10386,43,100.00,4,5417.57,2005-03-01,Resolved,1,3,2005,...,"C/ Moralzarzal, 86",Not Available,Madrid,Unknown,28034,Spain,EMEA,Freyre,Diego,Medium
2821,10397,34,62.24,1,2116.16,2005-03-28,Shipped,1,3,2005,...,1 rue Alsace-Lorraine,Not Available,Toulouse,Unknown,31000,France,EMEA,Roulet,Annette,Small
2822,10414,47,65.52,9,3079.44,2005-05-06,On Hold,2,5,2005,...,8616 Spinnaker Dr.,Not Available,Boston,MA,51003,USA,Unknown,Yoshido,Juri,Medium